---
swagger: "2.0"
info:
  description: "Sample API for managing durns. For this sample, you can use the api\
    \ key `special-key` to test the authorization filters."
  version: "1.0.0"
  title: "TJack durn manager"
  contact:
    email: "on.three.email@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
- name: "Durns"
  description: "Basic Durns management"
schemes:
- "http"
paths:
  /balance/vhost:
    post:
      tags:
      - "Durns"
      summary: "Get/Create account."
      description: "Get or create an account based on IRC hostmask."
      operationId: "getDurnsFromVHost"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Vhost to fetch"
        required: true
        schema:
          $ref: "#/definitions/VHost"
      responses:
        200:
          description: "Account found."
          schema:
            $ref: "#/definitions/Account"
        201:
          description: "Account created."
          schema:
            $ref: "#/definitions/Account"
      x-swagger-router-controller: "Durns"
  /balance/acccount/{address}:
    get:
      tags:
      - "Durns"
      summary: "Get account by address."
      description: "Get account details by account address."
      operationId: "getDurnsFromAccount"
      produces:
      - "application/json"
      parameters:
      - name: "address"
        in: "path"
        description: "The account number we're requesting info on."
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Account"
        400:
          description: "Account not found"
      x-swagger-router-controller: "Durns"
  /pay/account:
    post:
      tags:
      - "Durns"
      summary: "Create a payment."
      description: "Send coins from one user to another using account numbers."
      operationId: "createPaymentByAccount"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/definitions/AccountPayment"
      - in: header
        name: X-API-KEY
        type: string
        required: true
      responses:
        200:
          description: "Successful payment"
          schema:
            $ref: "#/definitions/PaymentComplete"
        400:
          description: "Incorrect API Key"
        401:
          description: "Invalid vhost"
        402:
          description: "Insufficient funds"
      security:
      - ApiKeyAuth: []
      x-swagger-router-controller: "Durns"
  /pay/vhost:
    post:
      tags:
      - "Durns"
      summary: "Create a payment."
      description: "Send coins from one user to another using vhosts."
      operationId: "createPaymentByVhost"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/definitions/VHostPayment"
      - in: header
        name: X-API-KEY
        type: string
        required: true
      responses:
        200:
          description: "Successful payment"
          schema:
            $ref: "#/definitions/PaymentComplete"
        400:
          description: "Incorrect API Key"
        401:
          description: "Invalid address"
        402:
          description: "Insufficient funds"
      security:
      - ApiKeyAuth: []
      x-swagger-router-controller: "Durns"
  /pick:
    get:
      tags:
      - "Durns"
      summary: "Update system."
      description: "Upon IRC utterance, this api should be called by a bot."
      operationId: "pickVHost"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "IRC post+vhost to update system."
        required: true
        schema:
          $ref: "#/definitions/Utterance"
      responses:
        200:
          description: "successful operation"
      security:
      - ApiKeyAuth: []
      x-swagger-router-controller: "Durns"
securityDefinitions:
  ApiKeyAuth:
    type: "apiKey"
    name: "X-API-KEY"
    in: "header"
definitions:
  VHost:
    type: "object"
    properties:
      vhost:
        type: "string"
        example: "~tjack@wow.such.durns"
  Account:
    type: "object"
    properties:
      vhost:
        type: "string"
      address:
        type: "string"
      balance:
        type: "number"
  AccountPayment:
    type: "object"
    properties:
      from:
        type: "string"
        example: "xxx-xxx-xxx-xxx"
      to:
        type: "string"
        example: "xxx-xxx-xxx-xxx"
      amount:
        type: "number"
        example: 100.5
  VHostPayment:
    type: "object"
    properties:
      from:
        type: "string"
        example: "~tjack@wow.such.durns"
      to:
        type: "string"
        example: "~tjack@wow.such.durns"
      amount:
        type: "number"
        example: 100.5
  PaymentComplete:
    type: "object"
    properties:
      from:
        type: "object"
        properties:
          vhost:
            type: "string"
            example: "~tjack@wow.such.durns"
          address:
            type: "string"
            example: "xxx-xxx-xxx-xxx"
          balance:
            type: "number"
            example: "100.05"
      to:
        type: "object"
        properties:
          vhost:
            type: "string"
            example: "~tjack2@wow.such.durns"
          address:
            type: "string"
            example: "yyy-yyy-yyy-yyy"
          balance:
            type: "number"
            example: "100.05"
  Utterance:
    type: "object"
    properties:
      vhost:
        type: "string"
        example: "~tjack@wow.such.durns"
      nick:
        type: "string"
        example: "tjack"
      post:
        type: "string"
        example: "Wow, such durns!"
